import type { Metadata } from "next";
import "./globals.css";
import {
  getMergedHomeHeroFrame,
  getMergedLayoutSpacing,
} from "@/lib/site-content";
import type { LayoutSpacing } from "@/lib/site-layout-spacing";

const siteDescription =
  "Curated fine-art photography and editions. E-commerce experience for collectors.";

function stripTrailingSlash(s: string) {
  return s.replace(/\/+$/, "");
}

/** Crawlers require absolute HTTPS image URLs — avoid localhost URLs on Vercel when env omits NEXT_PUBLIC_SITE_URL. */
function resolveMetadataBase(): URL {
  const siteUrl = stripTrailingSlash(
    process.env.NEXT_PUBLIC_SITE_URL?.trim() ?? "",
  );
  if (siteUrl.startsWith("http")) return new URL(siteUrl);

  const productionHostRaw =
    process.env.VERCEL_PROJECT_PRODUCTION_URL?.trim() ??
    process.env.VERCEL_URL?.trim();
  if (productionHostRaw) {
    const host = stripTrailingSlash(
      productionHostRaw.replace(/^https?:\/\//, ""),
    );
    return new URL(`https://${host}`);
  }

  return new URL("http://localhost:3000");
}

const metadataBase = resolveMetadataBase();

/**
 * Overrides must beat `:root` tokens from `globals.css`. Inline `style` on `<html>` is not reliable
 * with the App Router / hydration path here; a late `<style>` block keeps spacing editor changes visible.
 */
function siteThemeCss(heroTopPx: number, spacing: LayoutSpacing): string {
  const top = Number.isFinite(heroTopPx) ? heroTopPx : 116;
  return `:root {
  --home-hero-top: ${top}px;
  --gallery-gutter-x: clamp(1rem, 4vw, ${spacing.mainGutterMaxPx}px);
  --gallery-section-pad-bottom: ${spacing.sectionPadBottomPx}px;
  --gallery-detail-gap: clamp(1.5rem, 4vw, ${spacing.detailGapMaxPx}px);
  --gallery-gutter-index: max(${spacing.curateIndexGutterMinPx}px, 2.25vw);
  --site-rail: clamp(14rem, calc(11vw + 6.5rem), ${spacing.siteRailMaxRem}rem);
  --home-caption-mt: clamp(6px, 1.5vw, ${spacing.homeCaptionBelowMaxPx}px);
  --checkout-form-py: clamp(3rem, 8vw, ${spacing.checkoutFormPyMaxPx}px);
  --checkout-empty-py: clamp(4rem, 12vw, ${spacing.checkoutEmptyPyMaxPx}px);
  --gallery-grid-gap-x: ${spacing.gridGapXPx}px;
  --gallery-grid-gap-y-sm: ${spacing.gridGapYSmPx}px;
  --gallery-grid-gap-y-lg: ${spacing.gridGapYLgPx}px;
  --legal-page-py: ${spacing.legalPagePyPx}px;
}`;
}

/** Root reads hero frame CSS vars from Blob/overrides — must stay dynamic when Blob-linked. */
export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  metadataBase,
  title: {
    default: "Raivis Deutschman - Fine Art",
    template: "%s · Raivis Deutschman",
  },
  description: siteDescription,
  // Icons: `src/app/icon.svg` + `apple-icon.svg` from `public/images/logo.svg`
  openGraph: {
    title: "Raivis Deutschman - Fine Art",
    description: siteDescription,
    type: "website",
    locale: "en_US",
    siteName: "Raivis Deutschman",
    // og:image: generated by src/app/opengraph-image.tsx (1200×630 for WhatsApp/min-size rules)
  },
  twitter: {
    card: "summary_large_image",
    title: "Raivis Deutschman - Fine Art",
    description: siteDescription,
    // twitter:image: generated by src/app/twitter-image.tsx
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [heroFrame, spacing] = await Promise.all([
    getMergedHomeHeroFrame(),
    getMergedLayoutSpacing(),
  ]);
  const { topPaddingDesktopPx } = heroFrame;

  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col font-sans">
        <style dangerouslySetInnerHTML={{ __html: siteThemeCss(topPaddingDesktopPx, spacing) }} />
        {children}
      </body>
    </html>
  );
}
