import type { Metadata } from "next";
import type { CSSProperties } from "react";
import "./globals.css";
import { getMergedHomeHeroFrame } from "@/lib/site-content";

const siteDescription =
  "Curated fine-art photography and editions. E-commerce experience for collectors.";

function stripTrailingSlash(s: string) {
  return s.replace(/\/+$/, "");
}

/** Crawlers require absolute HTTPS image URLs — avoid localhost URLs on Vercel when env omits NEXT_PUBLIC_SITE_URL. */
function resolveMetadataBase(): URL {
  const siteUrl = stripTrailingSlash(
    process.env.NEXT_PUBLIC_SITE_URL?.trim() ?? "",
  );
  if (siteUrl.startsWith("http")) return new URL(siteUrl);

  const productionHostRaw =
    process.env.VERCEL_PROJECT_PRODUCTION_URL?.trim() ??
    process.env.VERCEL_URL?.trim();
  if (productionHostRaw) {
    const host = stripTrailingSlash(
      productionHostRaw.replace(/^https?:\/\//, ""),
    );
    return new URL(`https://${host}`);
  }

  return new URL("http://localhost:3000");
}

const metadataBase = resolveMetadataBase();

export const metadata: Metadata = {
  metadataBase,
  title: {
    default: "Raivis Deutschman - Fine Art",
    template: "%s — Raivis Deutschman",
  },
  description: siteDescription,
  // Icons: `src/app/icon.png` + `apple-icon.png` (replaces Next.js default triangle favicon)
  openGraph: {
    title: "Raivis Deutschman - Fine Art",
    description: siteDescription,
    type: "website",
    locale: "en_US",
    siteName: "Raivis Deutschman",
    // og:image: generated by src/app/opengraph-image.tsx (1200×630 for WhatsApp/min-size rules)
  },
  twitter: {
    card: "summary_large_image",
    title: "Raivis Deutschman - Fine Art",
    description: siteDescription,
    // twitter:image: generated by src/app/twitter-image.tsx
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { topPaddingDesktopPx } = getMergedHomeHeroFrame();
  const htmlStyle = {
    "--home-hero-top": `${topPaddingDesktopPx}px`,
  } as CSSProperties;

  return (
    <html lang="en" className="h-full antialiased" style={htmlStyle}>
      <body className="min-h-full flex flex-col font-sans">{children}</body>
    </html>
  );
}
